# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-12 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=27, verbose_name='Nama')),
                ('alamat', models.CharField(max_length=100, verbose_name='Alamat')),
                ('kontak', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100, verbose_name='Judul')),
                ('kategori', models.CharField(max_length=100, verbose_name='Kategori')),
                ('tahun', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing_time', models.TimeField()),
                ('showing_date', models.DateField()),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieTheater.movie')),
            ],
        ),
        migrations.CreateModel(
            name='theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=27, verbose_name='Nama')),
                ('kapasitas', models.IntegerField()),
                ('cinemas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieTheater.cinema')),
                ('showings', models.ManyToManyField(to='MovieTheater.showing')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kursi', models.CharField(max_length=10)),
                ('harga', models.IntegerField()),
                ('showings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieTheater.showing')),
            ],
        ),
    ]
